Make sure set{Suspended,Resumed} get called from main thread
ubports/qtubuntu pull request #14
Opened 2020-01-03 16:33 UTC by peat-psuwit

appStateController's set{Suspended,Resumed} are called from platform
-api's callback, which seem to be called from a different thread.

To make sure correct event ordering with setFocused (which is called
from customEvent), the appStateController is converted to a QObject, and
the callback is changed to invoke these method using QueuedConnection.

2020-01-05 10:22 UTC, Flohack74 commented
Hi, yes sure! That would totally rock, its already very annyoing when TELEports still thinks its suspended, because we then stop the server connection. So you will wait forever... I think we are the only APp that uses it so aggressively. So I will do tonight.

2020-01-07 18:06 UTC, UniversalSuperBox requested changes

2020-01-07 18:06 UTC, UniversalSuperBox commented on src/ubuntumirclient/qmirclientintegration.cpp
> +    // Make sure calls to appStateController happens on the main thread.
Make sure calls [...] *happen*

2020-01-07 18:15 UTC, peat-psuwit commented on src/ubuntumirclient/qmirclientintegration.cpp
> +    // Make sure calls to appStateController happens on the main thread.
Pardon my English grammar. 🤦

2020-01-07 21:27 UTC, Flohack74 approved these changes
I tested it on OPO for one day and its a significant improvement in TELEports now correctly knowing when to disconnect or reconnect to the servers.

2020-01-07 22:47 UTC, mariogrip approved these changes
LGTM :+1:

2020-01-09 02:18 UTC, UniversalSuperBox commented
I've installed this on my main phone to try it out. I'll come back tomorrow.

2020-01-09 21:19 UTC, Flohack74 commented
I hope we can merge this soon, I updated again to latest devel and immediately it starts failing again... ;)

2020-01-10 01:22 UTC, UniversalSuperBox approved these changes
Everything seems to work here.

2020-01-10 01:22 UTC, merged

2020-01-10 10:01 UTC, Flohack74 commented
Yeah it works very well. Thanks so much @peat-psuwit !